FROM golang:1.21-bullseye AS builder
WORKDIR /signatory
COPY . .
RUN apt-get update && apt-get install -y
RUN make

FROM amazonlinux:2023
WORKDIR /signatory
# Install necessary runtime dependencies
RUN dnf update -y
COPY --from=builder /signatory/signatory.yaml /signatory/signatory.yaml
COPY --from=builder /signatory/signatory /usr/bin/signatory
COPY --from=builder /signatory/signatory-cli /usr/bin/signatory-cli

ENTRYPOINT ["/usr/bin/signatory"]
CMD [ "-c", "/signatory/signatory.yaml" ] 